/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ppractica2016_200915715;

import ArchivosXml.*;
import ArchivosCodigo.*;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.io.StringReader;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author enrique
 */
public class Ide extends javax.swing.JFrame {
    
    int conta=1;
    int conta2 = 1;
    String var="1."+"\n";
    String var2="1."+"\n";
    String var3="";
    static String prueva="";
    String Amarillo="";
    /**
     * Creates new form Ide
     */
    public Ide() {
        try {
            initComponents();
            //setSize(600,620);
            jTextArea3.setText("1.");
            jTextArea4.setText("1.");
            jTextArea3.setBorder(new LineBorder(Color.WHITE,0));
            jTextArea3.setBackground(Color.WHITE);
            //var="";
            /**/
            /**/
            
            //ArchivosXml lexicoXml = new ArchivosXml(new StringReader(jTextArea1.getText()));
            ArchivosXml lexicoXml = new ArchivosXml(new FileInputStream("src/Archivos_De_Prueba/Entradas/Entrada1/Entrada1.practica1"));
            ParseXml semanticoXml = new ParseXml(lexicoXml);
            try {
                semanticoXml.parse();
            } catch (Exception ex) {
                Logger.getLogger(Ide.class.getName()).log(Level.SEVERE, null, ex);
            }
            for(int h=0;ParseXml.carpetas.size()-1>=h;h++){
                System.out.println(ParseXml.carpetas.get(h));
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ide.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 235, 593));

        jPanel4.setLayout(null);

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(370, 80, 101, 29);

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(370, 120, 101, 29);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setColumns(0);
        jTextArea3.setRows(0);
        jTextArea3.setBorder(null);
        jTextArea3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea3.setEnabled(false);
        jTextArea3.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(jTextArea3);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(40, 20, 31, 560);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(70, 20, 269, 560);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setColumns(0);
        jTextArea4.setRows(0);
        jTextArea4.setBorder(null);
        jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextArea4.setEnabled(false);
        jTextArea4.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(510, 10, 30, 570);

        jScrollPane6.setViewportView(jEditorPane1);

        jPanel4.add(jScrollPane6);
        jScrollPane6.setBounds(540, 10, 250, 520);

        jTabbedPane1.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel5);
        jTabbedPane1.addTab("tab3", jTabbedPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 910, -1));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Reportes");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Abrir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArchivosCodigo lexicoXml = new ArchivosCodigo(new StringReader(jTextArea1.getText()));
            ParseCodigo semanticoXml = new ParseCodigo(lexicoXml);
        try {
            semanticoXml.parse();
        } catch (Exception ex) {
            Logger.getLogger(Ide.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        for(int k =0;ParseCodigo.programa.size()-1>=k;k++){
            
            try{
                   if(Integer.valueOf((String) ParseCodigo.programa.get(k))>=0){
                  System.out.println(ParseCodigo.programa.get(k) +" "+ k );
                
            }
            
            }catch(Exception e){
               
            }
            
         
            
            
             System.out.println(ParseCodigo.programa.get(k) +" "+ k );
                if(ParseCodigo.programa.get(k).equals("importar") ||ParseCodigo.programa.get(k).equals("publico") || ParseCodigo.programa.get(k).equals("privado") ||ParseCodigo.programa.get(k).equals("protegido") || ParseCodigo.programa.get(k).equals("clase") || ParseCodigo.programa.get(k).equals("heredar")  ){
     //System.out.println("esta el <");
     prueva="&lt;";
    jEditorPane1.setContentType("text/html");
         Amarillo=Amarillo+("<font color=\"9A13D4\">"+ParseCodigo.programa.get(k)+"</font>");
    jEditorPane1.setText(Amarillo);
     }
      if(ParseCodigo.programa.get(k).equals("int")||ParseCodigo.programa.get(k).equals("double")||ParseCodigo.programa.get(k).equals("string")||ParseCodigo.programa.get(k).equals("char")||ParseCodigo.programa.get(k).equals("bool")||ParseCodigo.programa.get(k).equals("void") ||
               ParseCodigo.programa.get(k).equals("super")|| ParseCodigo.programa.get(k).equals("@override")|| ParseCodigo.programa.get(k).equals("nuevo")|| ParseCodigo.programa.get(k).equals("retornar")||
               ParseCodigo.programa.get(k).equals("principal")|| ParseCodigo.programa.get(k).equals("SI") ||  ParseCodigo.programa.get(k).equals("SINO_SI")|| ParseCodigo.programa.get(k).equals("SINO")|| ParseCodigo.programa.get(k).equals("INTERRUPTOR")|| ParseCodigo.programa.get(k).equals("CASO")|| ParseCodigo.programa.get(k).equals("DEFECTO")|| ParseCodigo.programa.get(k).equals("MIENTRAS")|| ParseCodigo.programa.get(k).equals("HACER")|| ParseCodigo.programa.get(k).equals("CONTINUAR")|| ParseCodigo.programa.get(k).equals("SALIR")){
            jEditorPane1.setContentType("text/html");
            Amarillo=Amarillo+("<font color=\"3564E5\">"+ParseCodigo.programa.get(k)+"</font>");
            jEditorPane1.setText(Amarillo);
      
      }
      
       if(ParseCodigo.programa.get(k).equals("+")||ParseCodigo.programa.get(k).equals("-")||ParseCodigo.programa.get(k).equals("*")||ParseCodigo.programa.get(k).equals("/")||ParseCodigo.programa.get(k).equals("++")||ParseCodigo.programa.get(k).equals("--") ||
             ParseCodigo.programa.get(k).equals(">") || ParseCodigo.programa.get(k).equals("<") || ParseCodigo.programa.get(k).equals(">=")||ParseCodigo.programa.get(k).equals("<=")||ParseCodigo.programa.get(k).equals("==")||ParseCodigo.programa.get(k).equals("!=")||ParseCodigo.programa.get(k).equals("(") ||ParseCodigo.programa.get(k).equals(")") ||
                ParseCodigo.programa.get(k).equals("||")|| ParseCodigo.programa.get(k).equals("&&")|| ParseCodigo.programa.get(k).equals("??")|| ParseCodigo.programa.get(k).equals("!!")){
            jEditorPane1.setContentType("text/html");
            Amarillo=Amarillo+("<font color=\"011958\">"+ParseCodigo.programa.get(k)+"</font>");
            jEditorPane1.setText(Amarillo);
      
      }
        if(ParseCodigo.programa.get(k).equals(";")|| ParseCodigo.programa.get(k).equals("[") || ParseCodigo.programa.get(k).equals("]")){
            jEditorPane1.setContentType("text/html");
            Amarillo=Amarillo+("<font color=\"000000\">"+ParseCodigo.programa.get(k)+"</font>");
            jEditorPane1.setText(Amarillo);
      
      }
          if(ParseCodigo.programa.get(k).equals("\"")){
            jEditorPane1.setContentType("text/html");
            Amarillo=Amarillo+("<font color=\"705019\">"+ParseCodigo.programa.get(k)+"</font>");
            jEditorPane1.setText(Amarillo);
      
      } 
      
                
            //jTextArea2.setText(String.valueOf(ParseCodigo.programa.get(k)));
           // var3= var3 +String.valueOf(ParseCodigo.programa.get(k));
        }
       //jTextArea2.setText(var3);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         FileNameExtensionFilter Filtro= new FileNameExtensionFilter("Archivos  usac","usac");
        
        JFileChooser nuevo= new JFileChooser();
        nuevo.setFileFilter(Filtro);
        int resultado = nuevo.showOpenDialog(null);
        if(resultado==JFileChooser.APPROVE_OPTION){
        File file=nuevo.getSelectedFile();
         try{
        FileReader Leer=new FileReader(String.valueOf(file));
        BufferedReader lector = new BufferedReader(Leer);
        String palabra2;
        String texto="";
        while((palabra2=lector.readLine())!=null){
        texto+=palabra2+"\n";
        conta++;
             var = var+ (conta+"." +"\n");
             jTextArea3.setText(var);

        }
        jTextArea1.setText(texto);
        }catch(Exception ex){




        }



        } 
             
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
      // Enter was pressed. Your code goes here.
             conta++;
             var = var+ (conta+"." +"\n");
             jTextArea3.setText(var);
             
   }
    }//GEN-LAST:event_jTextArea1KeyPressed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
