
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 09 19:41:34 CST 2016
//----------------------------------------------------

package ArchivosCodigo;

/** CUP generated class containing symbol constants. */
public class CaracterCodigo {
  /* terminals */
  public static final int Tk_CloseC = 54;
  public static final int Tk_minus = 25;
  public static final int Tk_Caso = 58;
  public static final int Tk_Over = 50;
  public static final int Tk_Super = 49;
  public static final int Tk_Cerrar = 33;
  public static final int Tk_Continuar = 65;
  public static final int Tk_new = 51;
  public static final int TK_Continuar = 62;
  public static final int Tk_private = 6;
  public static final int Tk_Error = 66;
  public static final int Tk_dif = 31;
  public static final int Tk_DobleB = 11;
  public static final int Tk_char = 18;
  public static final int Tk_xOr = 36;
  public static final int Tk_Comentario = 12;
  public static final int Tk_Mientras = 60;
  public static final int Tk_clase = 8;
  public static final int Tk_return = 64;
  public static final int Tk_menor = 27;
  public static final int Tk_Hacer = 61;
  public static final int Tk_Comillas = 38;
  public static final int Tk_Exit = 63;
  public static final int Tk_puntoComa = 48;
  public static final int Tk_Close = 40;
  public static final int Tk_mayor = 26;
  public static final int Tk_Inter = 57;
  public static final int Tk_import = 2;
  public static final int Tk_Asig = 47;
  public static final int Tk_bool = 16;
  public static final int Tk_SiNoSi = 55;
  public static final int EOF = 0;
  public static final int Tk_Coma = 41;
  public static final int Tk_suma = 20;
  public static final int Tk_mayorq = 28;
  public static final int Tk_plus = 24;
  public static final int error = 1;
  public static final int Tk_Firts = 52;
  public static final int Tk_public = 5;
  public static final int Tk_And = 37;
  public static final int Tk_Not = 34;
  public static final int Tk_multi = 23;
  public static final int Tk_protect = 7;
  public static final int Tk_true = 45;
  public static final int Tk_Abrir = 32;
  public static final int Tk_string = 14;
  public static final int Tk_false = 46;
  public static final int Tk_heredar = 10;
  public static final int Tk_void = 19;
  public static final int Tk_SiNo = 56;
  public static final int Tk_print = 43;
  public static final int Tk_name = 9;
  public static final int Tk_Si = 53;
  public static final int Tk_mientras = 44;
  public static final int Tk_Open = 39;
  public static final int Tk_int = 17;
  public static final int Tk_igualIgual = 30;
  public static final int Tk_ruta = 4;
  public static final int Tk_Igual = 42;
  public static final int Tk_abrir = 3;
  public static final int Tk_Defec = 59;
  public static final int Tk_menorq = 29;
  public static final int Tk_OpenC = 13;
  public static final int Tk_resta = 21;
  public static final int Tk_Or = 35;
  public static final int Tk_div = 22;
  public static final int Tk_double = 15;
}

