
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 13 13:54:47 CST 2016
//----------------------------------------------------

package ArchivosCodigo;

/** CUP generated class containing symbol constants. */
public class CaracterCodigo {
  /* terminals */
  public static final int Tk_CloseC = 55;
  public static final int Tk_minus = 26;
  public static final int Tk_Caso = 60;
  public static final int Tk_Over = 51;
  public static final int Tk_Super = 50;
  public static final int Tk_Cerrar = 34;
  public static final int Tk_Continuar = 67;
  public static final int Tk_new = 52;
  public static final int TK_Continuar = 64;
  public static final int Tk_private = 6;
  public static final int Tk_Error = 68;
  public static final int Tk_dif = 32;
  public static final int Tk_DobleB = 12;
  public static final int Tk_char = 19;
  public static final int Tk_xOr = 37;
  public static final int Tk_Comentario = 13;
  public static final int Tk_Mientras = 62;
  public static final int Tk_clase = 8;
  public static final int Tk_return = 66;
  public static final int Tk_menor = 28;
  public static final int Tk_Hacer = 63;
  public static final int Tk_Comillas = 39;
  public static final int Tk_Exit = 65;
  public static final int Tk_puntoComa = 49;
  public static final int Tk_Close = 41;
  public static final int Tk_mayor = 27;
  public static final int Tk_Inter = 59;
  public static final int Tk_import = 2;
  public static final int Tk_Asig = 48;
  public static final int Tk_bool = 17;
  public static final int Tk_SiNoSi = 57;
  public static final int EOF = 0;
  public static final int Tk_Coma = 42;
  public static final int Tk_suma = 21;
  public static final int Tk_mayorq = 29;
  public static final int Tk_plus = 25;
  public static final int error = 1;
  public static final int Tk_Firts = 53;
  public static final int Tk_public = 5;
  public static final int Tk_And = 38;
  public static final int Tk_Not = 35;
  public static final int Tk_multi = 24;
  public static final int Tk_protect = 7;
  public static final int Tk_true = 46;
  public static final int Tk_Abrir = 33;
  public static final int Tk_string = 15;
  public static final int Tk_false = 47;
  public static final int Tk_heredar = 11;
  public static final int Tk_void = 20;
  public static final int Tk_SiNo = 58;
  public static final int Tk_print = 44;
  public static final int Tk_name = 9;
  public static final int Tk_Si = 54;
  public static final int Tk_mientras = 45;
  public static final int Tk_Open = 40;
  public static final int Tk_Dosp = 56;
  public static final int Tk_int = 18;
  public static final int Tk_igualIgual = 31;
  public static final int Tk_ruta = 4;
  public static final int Tk_Igual = 43;
  public static final int Tk_abrir = 3;
  public static final int Tk_Defec = 61;
  public static final int Tk_menorq = 30;
  public static final int Tk_OpenC = 14;
  public static final int Tk_resta = 22;
  public static final int Tk_Or = 36;
  public static final int Tk_Puntos = 10;
  public static final int Tk_div = 23;
  public static final int Tk_double = 16;
}

