
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 03 23:33:45 CST 2016
//----------------------------------------------------

package ArchivosXml;

/** CUP generated class containing symbol constants. */
public class CaracterXml {
  /* terminals */
  public static final int Tk_Name = 10;
  public static final int Tk_Arch = 7;
  public static final int Tk_Cont = 18;
  public static final int Tk_Ruta = 17;
  public static final int Tk_Files = 16;
  public static final int Tk_Guion = 12;
  public static final int Tk_Puntos = 19;
  public static final int Tk_Year = 15;
  public static final int EOF = 0;
  public static final int Tk_Error = 9;
  public static final int Tk_Dia = 13;
  public static final int Tk_Cerrar = 3;
  public static final int Tk_Comillas = 5;
  public static final int error = 1;
  public static final int Tk_Abrir = 2;
  public static final int Tk_Luga = 11;
  public static final int Tk_Diag = 4;
  public static final int Tk_Mes = 14;
  public static final int Tk_Date = 8;
  public static final int Tk_Proy = 6;
}

